name: Checkout Example Workflow

   on:
     push:
       branches:
         - main
     workflow_dispatch: # Позволяет запуск вручную

   jobs:
     checkout-job:
       runs-on: ubuntu-latest

       steps:
         # Шаг 1: Зачек-аутить репозиторий
         - name: Checkout repository
           uses: actions/checkout@v3

         # Шаг 2: Выполнить команды с кодом репозитория
         - name: List files in repository
           run: ls -la
